spring.application.name=spring-postgres-crud
spring.datasource.url=jdbc:postgresql://localhost:5432/sampledb
spring.datasource.username=user
spring.datasource.password=userpassword
spring.jpa.hibernate.ddl-auto=none