services:
  app:
    container_name: "app-container"
    build: . # Dockerfile path
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./ # Source code file path
        target: /app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: sampledb
  db:
    container_name: "db-container"
    image: postgres:17.5-alpine3.22
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: db-volume
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: sampledb
volumes:
  db-volume:
